# analyze/summarizer.py

import os
import sys

# Add root path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.settings import settings

# Lazy client initialization - only create when needed
_client = None


def _get_client():
    """Get OpenAI client, creating it lazily on first use."""
    global _client
    if _client is None:
        if not settings.OPENAI_API_KEY:
            raise ValueError(
                "OPENAI_API_KEY is required for summarization. "
                "Set it in your .env file or environment."
            )
        from openai import OpenAI
        _client = OpenAI(api_key=settings.OPENAI_API_KEY)
    return _client


def load_prompt_template(prompt_path):
    if not os.path.exists(prompt_path):
        raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
    with open(prompt_path, "r") as f:
        return f.read()


def summarize_section(section_name, section_text, prompt_path, model="gpt-4o"):
    """
    Summarize a given section of a 10-K filing using a prompt template.

    Args:
        section_name (str): Label for the section (e.g., "Risk Factors")
        section_text (str): Extracted section text
        prompt_path (str): Path to prompt template
        model (str): OpenAI model to use (default = gpt-4o)

    Returns:
        str: Summary generated by GPT
    """
    print(f"🧠 Generating summary for: {section_name}")

    prompt_template = load_prompt_template(prompt_path)
    full_prompt = prompt_template.replace("{{SECTION_TEXT}}", section_text)

    client = _get_client()
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are a professional financial analyst."},
            {"role": "user", "content": full_prompt}
        ],
        temperature=0.3,
        max_tokens=400
    )

    summary = response.choices[0].message.content.strip()
    print("✅ Summary generated.")
    return summary


def save_summary(summary_text, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(summary_text)
    print(f"📄 Summary saved to: {output_path}")




